[package]
name = "json-parse-wasm"
version = "0.1.0"
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3"
serde = "1"
serde_derive = "1"
serde_json = "1"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] } 
wee_alloc = "0.4"

[profile.release]
lto = true
opt-level = 'z'
